#!/usr/bin/env bash
# Launch TLauncher with NVIDIA PRIME render offload on hybrid-GPU laptops.
# Does not change system drivers or global GLX settings.

export __NV_PRIME_RENDER_OFFLOAD=1
export __NV_PRIME_RENDER_OFFLOAD_PROVIDER="${TL_NVIDIA_PROVIDER:-NVIDIA-G0}"
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export __VK_LAYER_NV_optimus=NVIDIA_only

TL_JAVA="${TL_JAVA:-/usr/games/tlauncher/lib/jvm/jre/bin/java}"
TL_JAR="${TL_JAR:-/usr/games/tlauncher/starter-core.jar}"

exec "$TL_JAVA" -Dfile.encoding=UTF8 -jar "$TL_JAR" "$@"
